# Generated by Django 3.2.9 on 2022-07-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attandencemodel',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
